### ISSUE TITLE
Consider publishing prebuilt binaries

### ISSUE THREAD

**Issue by cmoog** [haze/rehype-tree-sitter#2]
The current approach that relies on `cargo` at install-time has a few drawbacks. Firstly, it requires having a full rust toolchain installed on the build machine. The implicit dependence on the specific compiler version could be the cause of hairy bugs. Secondly, it implicitly requires network access at install-time to fetch the cargo dependencies. This makes usage with network blocked build tooling such as `nix` difficult. Thirdly, it consumes a non-trivial amount of CPU to perform cargo release builds on every install.

I realize that publishing opaque binaries isn't ideal, but it seems to be the standard for cases such as this. See: esbuild, swc, etc.

**Comment by haze** [comment]
This is true! I could precompile binaries for a matrix of the most popular operating system and architectures. I simply just haven't gotten around to it yet.

Thanks for opening this issue, I'll close it when I make those available.

**Comment by haze** [comment]
Hi @cmoog, can you let me know if the latest version of the package solves this for you?

**Comment by cmoog** [comment]
Yes this looks like it fixed my issue. Would also be great to get an artifact for linux aarch64.

Thanks for adding this!

**Comment by haze** [comment]
Done in [5a7e74b](https://github.com/haze/rehype-tree-sitter/commit/5a7e74b49348e62eab6a8cd8165bfa2f49593c84)!
